"""Add IP tracking and blacklist tables

Revision ID: 00618a6352a0
Revises: aa082992ec37
Create Date: 2025-07-29 07:17:21.586827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00618a6352a0'
down_revision = 'aa082992ec37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
