"""Add order_number column to Order model

Revision ID: 65cbf933c4fb
Revises: 
Create Date: 2025-06-27 15:18:53.472528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65cbf933c4fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
